name: Install from github zipball (stable branch)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install tq
      run: |
        sudo apt-get install python3-setuptools
        sudo -H pip3 install --upgrade pip
        sudo -H pip3 install https://github.com/plainas/tq/zipball/stable
    - name: Run tq
      run: |
        echo "ok, which version are we at...."
        tq -v
        echo "Let's check what's on hacker news today"
        curl https://news.ycombinator.com/news | tq -tj ".title a"
